In [67]:
import numpy as np

In [68]:
myfile = [
    'I am Hamza Ali',
    'I am living in Mansehra',
    'I love Pakistan',
    'I am a Data Scientist',
    'My father name is Zulqarnain'
]

In [69]:
import tensorflow as tf
import keras
from keras.preprocessing.text import Tokenizer

In [70]:
Tokenizer = Tokenizer(oov_token='nothing else')

In [71]:
Tokenizer.fit_on_texts(myfile)

In [72]:
Tokenizer.word_index

{'nothing else': 1,
 'i': 2,
 'am': 3,
 'hamza': 4,
 'ali': 5,
 'living': 6,
 'in': 7,
 'mansehra': 8,
 'love': 9,
 'pakistan': 10,
 'a': 11,
 'data': 12,
 'scientist': 13,
 'my': 14,
 'father': 15,
 'name': 16,
 'is': 17,
 'zulqarnain': 18}

In [73]:
Tokenizer.word_counts

OrderedDict([('i', 4),
             ('am', 3),
             ('hamza', 1),
             ('ali', 1),
             ('living', 1),
             ('in', 1),
             ('mansehra', 1),
             ('love', 1),
             ('pakistan', 1),
             ('a', 1),
             ('data', 1),
             ('scientist', 1),
             ('my', 1),
             ('father', 1),
             ('name', 1),
             ('is', 1),
             ('zulqarnain', 1)])

In [74]:
Tokenizer.document_count

5

In [75]:
sequence = Tokenizer.texts_to_sequences(myfile)
sequence

[[2, 3, 4, 5],
 [2, 3, 6, 7, 8],
 [2, 9, 10],
 [2, 3, 11, 12, 13],
 [14, 15, 16, 17, 18]]

In [76]:
from keras.utils import pad_sequences
sequence = pad_sequences(sequence, padding='post')

In [77]:
sequence

array([[ 2,  3,  4,  5,  0],
       [ 2,  3,  6,  7,  8],
       [ 2,  9, 10,  0,  0],
       [ 2,  3, 11, 12, 13],
       [14, 15, 16, 17, 18]])

### Here we willuse embedding in keras 

In [78]:
from keras.layers import Embedding, Dense
from keras.models import Sequential

In [79]:
myfile2 = [
    'I am Hamza Ali',
    'I am living in Mansehra',
    'I love Pakistan',
    'I am a Data Scientist',
    'My father name is Zulqarnain',
    'Now I am studying Computer Engineering',
    'Pakistan Zindabad',
    'Alhamdulillah',
    'Today is Friday'
]

In [80]:
Tokenizer.fit_on_texts(myfile2)

In [81]:
len(Tokenizer.index_word)

26

In [82]:
sequence2 = Tokenizer.texts_to_sequences(myfile2)
sequence2

[[2, 3, 6, 7],
 [2, 3, 8, 9, 10],
 [2, 11, 4],
 [2, 3, 12, 13, 14],
 [15, 16, 17, 5, 18],
 [19, 2, 3, 20, 21, 22],
 [4, 23],
 [24],
 [25, 5, 26]]

In [83]:
Tokenizer.document_count

14

In [84]:
sequences = pad_sequences(sequence2 , padding='post' )
sequences

array([[ 2,  3,  6,  7,  0,  0],
       [ 2,  3,  8,  9, 10,  0],
       [ 2, 11,  4,  0,  0,  0],
       [ 2,  3, 12, 13, 14,  0],
       [15, 16, 17,  5, 18,  0],
       [19,  2,  3, 20, 21, 22],
       [ 4, 23,  0,  0,  0,  0],
       [24,  0,  0,  0,  0,  0],
       [25,  5, 26,  0,  0,  0]])

In [85]:
sequences.shape

(9, 6)

In [86]:
len(Tokenizer.word_index)

26

### Embedding uniquewords = 25, outputmatrix = [2,2], inputlength means maxlength of word = 6

In [87]:
vocab_size = 27
embedding_dim = 2
max_sequence_length = 6

In [88]:
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=max_sequence_length))
model.summary()

Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_8 (Embedding)     (None, 6, 2)              54        
                                                                 
Total params: 54 (216.00 Byte)
Trainable params: 54 (216.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [89]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [90]:
pred = model.predict(sequences)
print(pred)

1/1 [==============================] - 0s 61ms/step
[[[ 0.01425892  0.04953107]
  [-0.01784085  0.02541028]
  [ 0.02136542  0.02859923]
  [ 0.00516356  0.03060845]
  [-0.02403837 -0.02037185]
  [-0.02403837 -0.02037185]]

 [[ 0.01425892  0.04953107]
  [-0.01784085  0.02541028]
  [-0.04433078  0.04116913]
  [ 0.02023501  0.04203645]
  [-0.02547871 -0.04237184]
  [-0.02403837 -0.02037185]]

 [[ 0.01425892  0.04953107]
  [ 0.03048917 -0.01824747]
  [-0.0286803  -0.00287217]
  [-0.02403837 -0.02037185]
  [-0.02403837 -0.02037185]
  [-0.02403837 -0.02037185]]

 [[ 0.01425892  0.04953107]
  [-0.01784085  0.02541028]
  [ 0.03726515 -0.03720424]
  [-0.03252614 -0.03721142]
  [ 0.03169713 -0.04874166]
  [-0.02403837 -0.02037185]]

 [[ 0.00667368  0.00495888]
  [-0.01539792 -0.0351084 ]
  [-0.00565504 -0.00821749]
  [-0.01379305 -0.01800972]
  [ 0.03671098 -0.03450634]
  [-0.02403837 -0.02037185]]

 [[ 0.00832546 -0.0013544 ]
  [ 0.01425892  0.04953107]
  [-0.01784085  0.02541028]
  [ 0.00219246